db:
  host: host.docker.internal
  name: quay
  port: 5432
  user: quay
  password: quay
is_local: true
authentication:
  url: http://host.docker.internal:8081/auth
  realm: Test
  clientid: test-client-id
ENV: development
DEBUG: true
